spring:
  datasource: # 数据库连接配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.76.157.149:3306/lottery?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: lottery
    password: lottery123
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

